[package]
name = "racket-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"

# Testing config
[lib]
doctest = false
crate-type = ["cdylib"]

[[bin]]
name = "racket_rs"
path = "src/main.rs"
test = false
